CREATE TABLE INVITATIONS (
  ID           NUMBER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INVITEE      VARCHAR NOT NULL,
  EMAIL        VARCHAR NOT NULL
);

CREATE INDEX INVITATIONS_IDX
  ON INVITATIONS (EMAIL, EMAIL);