CREATE TABLE INVITATIONS (
  ID           INTEGER PRIMARY KEY NOT NULL,
  INVITEE      VARCHAR2(255)       NOT NULL,
  EMAIL        VARCHAR2(255)       NOT NULL
);

CREATE INDEX INVITATIONS_IDX
  ON INVITATIONS (EMAIL, EMAIL);